apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 10Gi  
  volumeMode: Filesystem  
  accessModes:
    - ReadWriteOnce 
  storageClassName: jenks
  local:
    path: /root/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 5Gi  
  storageClassName: jenks
